In [3]:
import numpy as np
import random

In [5]:
a = np.random.randn(100,50)

In [6]:
a

array([[-1.37622742,  0.16868809,  1.12503484, ...,  1.39649569,
        -0.90030796,  1.53596354],
       [-1.14707588,  1.02905765,  0.54642104, ...,  0.82671726,
         0.82030271,  0.89642049],
       [ 1.07483226,  1.41170643, -0.09743832, ...,  1.73153645,
        -0.40660858, -1.31875178],
       ...,
       [ 0.11812112,  0.74867749,  1.1832311 , ..., -0.97094117,
        -0.47327606,  0.60412664],
       [ 0.87120445,  0.44561001,  0.41629459, ...,  0.45223107,
         1.56813506,  0.09451163],
       [ 0.54682841,  0.85540101, -1.19458285, ..., -0.137631  ,
         1.4034458 , -0.35002638]])

In [8]:
expa = np.exp(a)

In [9]:
expa

array([[0.25252945, 1.18375086, 3.08032417, ..., 4.04101415, 0.40644447,
        4.64579979],
       [0.31756401, 2.7984275 , 1.72706087, ..., 2.28580271, 2.27118723,
        2.45081468],
       [2.92950147, 4.10295083, 0.90715829, ..., 5.64932718, 0.66590479,
        0.26746895],
       ...,
       [1.12538041, 2.11420212, 3.26490642, ..., 0.37872642, 0.62295807,
        1.82965356],
       [2.3897875 , 1.5614424 , 1.5163325 , ..., 1.57181511, 4.79769246,
        1.09912194],
       [1.72776455, 2.3523175 , 0.30283025, ..., 0.87142018, 4.06919748,
        0.7046695 ]])

In [18]:
p = expa/np.sum(expa,axis=1,keepdims=True) #axis=1; row-wise addition.(All elements in a row are added)

In [26]:
p.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.sum(expa,axis=1).shape

(100,)

In [30]:
np.sum(expa,axis=1,keepdims=True).shape

(100, 1)