In [1]:
import numpy as np
import random

In [2]:
a = np.random.randn(100,50)

In [3]:
a

array([[ 0.60615399, -0.8220143 , -0.604523  , ..., -1.3861188 ,
         0.75609962,  1.62401957],
       [-0.5065853 ,  0.33884578,  0.10184638, ..., -0.60700394,
        -0.37875831, -1.96188655],
       [ 0.28426073, -1.23953773,  0.55270622, ..., -1.85896676,
        -1.19810445,  1.34746078],
       ...,
       [-1.0575343 , -0.92882241, -0.75390203, ..., -2.53094774,
         0.95047302,  0.13662089],
       [ 1.12182997, -1.06687022,  0.02725476, ..., -0.11856111,
        -0.32292932, -0.13865688],
       [-0.48343326,  0.26972748,  2.37984174, ..., -1.32053759,
         0.10222565, -0.11944805]])

In [4]:
expa = np.exp(a)

In [5]:
expa

array([[ 1.83336667,  0.43954539,  0.54633496, ...,  0.25004389,
         2.12995237,  5.07344245],
       [ 0.6025496 ,  1.40332691,  1.10721337, ...,  0.54498122,
         0.68471108,  0.14059293],
       [ 1.32877934,  0.28951802,  1.73794994, ...,  0.15583356,
         0.30176568,  3.8476431 ],
       ...,
       [ 0.34731112,  0.39501861,  0.47052696, ...,  0.07958356,
         2.58693304,  1.14639346],
       [ 3.07046794,  0.34408374,  1.02762957, ...,  0.88819754,
         0.72402503,  0.87052667],
       [ 0.61666259,  1.3096075 , 10.80319297, ...,  0.26699173,
         1.10763338,  0.8874101 ]])

In [6]:
p = expa/np.sum(expa,axis=1,keepdims=True) #axis=1; row-wise addition.(All elements in a row are added)

In [7]:
p.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
p

array([[0.02270609, 0.00544373, 0.00676631, ..., 0.00309677, 0.02637927,
        0.06283414],
       [0.00983184, 0.02289818, 0.01806647, ..., 0.00889249, 0.01117248,
        0.00229406],
       [0.01468029, 0.00319858, 0.01920078, ..., 0.00172164, 0.00333389,
        0.04250857],
       ...,
       [0.00332586, 0.00378271, 0.00450578, ..., 0.00076209, 0.02477255,
        0.0109779 ],
       [0.03693525, 0.00413905, 0.01236155, ..., 0.0106843 , 0.00870944,
        0.01047173],
       [0.00830144, 0.01762979, 0.14543135, ..., 0.00359421, 0.01491083,
        0.01194621]])

In [9]:
np.sum(expa,axis=1).shape

(100,)

In [10]:
np.sum(expa,axis=1,keepdims=True).shape

(100, 1)